#!/bin/bash
# Cloud-Native Deployment Wizard - Final Part
# Template generation functions for all components

# This file contains the remaining functions for the wizard

generate_network_config() {
    echo "Generating network configuration..."
    
    local template="$TEMPLATE_DIR/networking/network-config.yml.j2"
    local output="$GENERATED_DIR/configs/network-config.yml"
    
    mkdir -p "$(dirname "$output")"
    
    if [[ -f "$template" ]]; then
        envsubst < "$template" > "$output"
        echo "  → $output"
    fi
}

generate_ceph_config() {
    echo "Generating Ceph configuration..."
    
    local template="$TEMPLATE_DIR/ceph/ceph-config.yml.j2"
    local output="$GENERATED_DIR/configs/ceph-config.yml"
    
    mkdir -p "$(dirname "$output")"
    
    if [[ -f "$template" ]]; then
        envsubst < "$template" > "$output"
        echo "  → $output"
    fi
}

generate_nexus_harbor_config() {
    echo "Generating Nexus/Harbor configuration..."
    
    local template="$TEMPLATE_DIR/nexus-harbor/group_vars.yml.j2"
    local output="$GENERATED_DIR/configs/nexus-harbor-config.yml"
    
    mkdir -p "$(dirname "$output")"
    
    if [[ -f "$template" ]]; then
        envsubst < "$template" > "$output"
        echo "  → $output"
    fi
}

generate_platform_config() {
    echo "Generating platform configuration..."
    
    local template="$TEMPLATE_DIR/platform/platform-config.yml.j2"
    local output="$GENERATED_DIR/configs/platform-config.yml"
    
    mkdir -p "$(dirname "$output")"
    
    if [[ -f "$template" ]]; then
        envsubst < "$template" > "$output"
        echo "  → $output"
    fi
}

generate_monitoring_config() {
    echo "Generating monitoring configuration..."
    
    local template="$TEMPLATE_DIR/monitoring/monitoring-config.yml.j2"
    local output="$GENERATED_DIR/configs/monitoring-config.yml"
    
    mkdir -p "$(dirname "$output")"
    
    if [[ -f "$template" ]]; then
        envsubst < "$template" > "$output"
        echo "  → $output"
    fi
}

generate_gitlab_config() {
    if [[ "$GITLAB_ENABLED" == "true" ]]; then
        echo "Generating GitLab configuration..."
        
        local template="$TEMPLATE_DIR/gitlab/gitlab-config.yml.j2"
        local output="$GENERATED_DIR/configs/gitlab-config.yml"
        
        mkdir -p "$(dirname "$output")"
        
        if [[ -f "$template" ]]; then
            envsubst < "$template" > "$output"
            echo "  → $output"
        fi
    fi
}

generate_minio_config() {
    if [[ "$MINIO_ENABLED" == "true" ]]; then
        echo "Generating MinIO configuration..."
        
        local template="$TEMPLATE_DIR/minio/minio-config.yml.j2"
        local output="$GENERATED_DIR/configs/minio-config.yml"
        
        mkdir -p "$(dirname "$output")"
        
        if [[ -f "$template" ]]; then
            envsubst < "$template" > "$output"
            echo "  → $output"
        fi
    fi
}

generate_scripts() {
    echo "Generating customized scripts..."
    
    # OS preparation script
    local osoutput="$GENERATED_DIR/scripts/os-prep/linux-hardening.sh"
    mkdir -p "$(dirname "$osoutput")"
    
    ssh ${OPS_LINUX_IP} "cat > ${osoutput} << 'OSSESSION'
#!/bin/bash
# OS Preparation Script - Generated by Wizard for ${CLUSTER_NAME}
# Customized IPs: ${MASTER_IPS} ${WORKER_IPS} ${LB_IPS}
# NTP Servers: ${DNS_SERVER_IPS}
# DNS Servers: ${DNS_SERVER_IPS}

set -euo pipefail

# Configuration from wizard
CLUSTER_NAME="${CLUSTER_NAME}"
DOMAIN_SUFFIX="${DOMAIN_SUFFIX}"
NTP_SERVERS=(${DNS_SERVER_IPS})
DNS_SERVERS=(${DNS_SERVER_IPS})
SEARCH_DOMAINS="${CLUSTER_NAME}.${DOMAIN_SUFFIX} ${DOMAIN_SUFFIX}"

# Master node IPs
MASTER_IPS=(${MASTER_IPS})
WORKER_IPS=(${WORKER_IPS})
LB_IPS=(${LB_IPS})
MON_IPS=(${MON_IPS})
OSD_IPS=(${OSD_IPS})
RGW_IP="${RGW_HOST_IP}"
NEXUS_IP="${NEXUS_HOST_IP}"
HARBOR_IP="${HARBOR_HOST_IP}"

# Function stubs
configure_ntp() {
    echo "Configuring NTP with servers: \${NTP_SERVERS[*]}"
    # Actual configuration would go here
}

configure_dns() {
    echo "Configuring DNS servers: \${DNS_SERVERS[*]}"
    # Actual configuration would go here
}

harden_os() {
    echo "Applying OS hardening for cluster: \${CLUSTER_NAME}"
    # Actual hardening commands would go here
}

# Main
configure_ntp
configure_dns
harden_os

echo "OS preparation complete for cluster: \${CLUSTER_NAME}"
OSSESSION"
    chmod +x "$osoutput" 2>/dev/null || true
    echo "  → $osoutput"
    
    # KubeSpray wrapper
    local ksoutput="$GENERATED_DIR/scripts/kubespray-deploy.sh"
    ssh ${OPS_LINUX_IP} "cat > ${ksoutput} << 'KSSCRIPT'
#!/bin/bash
set -euo pipefail

CLUSTER_NAME="${CLUSTER_NAME}"
INVENTORY_DIR="generated/inventory/\$CLUSTER_NAME"
KUBESPRAY_PATH="../kubespray"

echo "Deploying cluster: \$CLUSTER_NAME"
echo "Using inventory: \$INVENTORY_DIR"

# Pre-flight checks
ansible -i "\$INVENTORY_DIR/hosts.yml" all -m ping

# Run deployment
ansible-playbook -i "\$INVENTORY_DIR/hosts.yml" "\$KUBESPRAY_PATH/cluster.yml"

echo "Deployment complete!"
KSSCRIPT"
    chmod +x "$ksoutput" 2>/dev/null || true
    echo "  → $ksoutput"
    
    # HAProxy deployment script
    local haproxy_output="$GENERATED_DIR/scripts/networking/deploy-haproxy-keepalived.sh"
    mkdir -p "$(dirname "$haproxy_output")"
    
    ssh ${OPS_LINUX_IP} "cat > ${haproxy_output} << 'HAPROXYSCRIPT'
#!/bin/bash
set -euo pipefail

LB_IPS=({{ lb_ips }})
MASTER_IPS=({{ master_ips }})
WORKER_IPS=({{ worker_ips }})
VIP="${HAPROXY_VIP}"

echo "Deploying HAProxy + Keepalived..."
echo "LB IPs: \${LB_IPS[@]}"
echo "VIP: \${VIP}"
HAPROXYSCRIPT"
    chmod +x "$haproxy_output" 2>/dev/null || true
    echo "  → $haproxy_output"
}

generate_docs() {
    echo "Generating customized documentation..."
    
    # Network diagram
    local netout="$GENERATED_DIR/docs/architecture/network-diagram.md"
    mkdir -p "$(dirname "$netout")"
    
    cat > "$netout" << EOF
# Network Diagram - Customized for ${CLUSTER_NAME}

\`\`\`
IP ADDRESSING SCHEME
===================

# Management Cluster
Master Nodes:
${MASTER_IPS[@]}

Worker Nodes:
${WORKER_IPS[@]}

Load Balancers (HAProxy + keepalived):
${LB_IPS[@]} (VIP: ${HAPROXY_VIP} for API)

Ceph Monitor Nodes:
${MON_IPS[@]}

Ceph OSD Nodes:
${OSD_IPS[@]}

RGW (Object Gateway):
${RGW_HOST_IP}

Nexus Repository:
${NEXUS_HOST_IP}

Harbor Registry:
${HARBOR_HOST_IP}

Ops Servers:
- Linux: ${OPS_LINUX_IP}
- Windows: ${OPS_WINDOWS_IP}

Networks:
- Node Network: 10.1.0.0/16
- Service CIDR: ${SERVICE_CIDR}
- Pod CIDR: ${POD_CIDR}
- Ceph Public: ${CEPH_PUBLIC_CIDR}
- Ceph Cluster: ${CEPH_CLUSTER_CIDR}
- MetalLB Pool: ${METALLB_START}-${METALLB_END} (Application cluster only)
\`\`\`
EOF
    echo "  → $netout"
    
    # Repository list
    local repoout="$GENERATED_DIR/docs/prerequisites/repository-list.md"
    mkdir -p "$(dirname "$repoout")"
    
    cat > "$repoout" << EOF
# Repository and Registry List - Customized for ${CLUSTER_NAME}

## Container Registries
- Harbor: https://${HARBOR_HOST_IP}/
  - Projects: k8s-images, ceph-images, monitoring-images, platform-images, os-images

## Package Repositories (Nexus)
- APT (Ubuntu 22.04): http://${NEXUS_HOST_IP}:${NEXUS_HTTP_PORT}/repository/apt-ubuntu-hosted/
  - Components: main, universe, restricted, multiverse
- PyPI: http://${NEXUS_HOST_IP}:${NEXUS_PYPI_PORT}/repository/pypi-group/simple
- Helm: http://${NEXUS_HOST_IP}:${NEXUS_HELM_PORT}/repository/helm-hosted/
- YUM/Ceph: http://${NEXUS_HOST_IP}:${NEXUS_YUM_PORT}/repository/yum-hosted-ceph/

## Git Repositories
- GitLab: http://gitlab.${DOMAIN_SUFFIX}/
  - Infrastructure: k8s-manifests, helm-values, ansible-playbooks, scripts
  - Applications: [your-projects]

## Object Storage (S3 Compatible)
- Ceph RGW: http://${RGW_HOST_IP}/
  - Buckets: ${CLUSTER_NAME}-loki, ${CLUSTER_NAME}-velero, ${CLUSTER_NAME}-gitlab-backups
EOF
    echo "  → $repoout"
}

# Execute main function
main "$@"